// Code generated by mockery. DO NOT EDIT.

package mock

import (
	service "github.com/lianjin/campaign-center-api/server/service"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

// CreditCampaignReward provides a mock function with given fields: userID, campaignID, amount, currency
func (_m *MockAccountService) CreditCampaignReward(userID int64, campaignID int64, amount float64, currency string) (*service.RechargeResult, error) {
	ret := _m.Called(userID, campaignID, amount, currency)

	if len(ret) == 0 {
		panic("no return value specified for CreditCampaignReward")
	}

	var r0 *service.RechargeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64, float64, string) (*service.RechargeResult, error)); ok {
		return rf(userID, campaignID, amount, currency)
	}
	if rf, ok := ret.Get(0).(func(int64, int64, float64, string) *service.RechargeResult); ok {
		r0 = rf(userID, campaignID, amount, currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.RechargeResult)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64, float64, string) error); ok {
		r1 = rf(userID, campaignID, amount, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSummary provides a mock function with given fields: userID, currency
func (_m *MockAccountService) GetSummary(userID int64, currency string) (*service.AccountSummary, error) {
	ret := _m.Called(userID, currency)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 *service.AccountSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (*service.AccountSummary, error)); ok {
		return rf(userID, currency)
	}
	if rf, ok := ret.Get(0).(func(int64, string) *service.AccountSummary); ok {
		r0 = rf(userID, currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AccountSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(userID, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTransactions provides a mock function with given fields: userID, txnType, cursorID, limit
func (_m *MockAccountService) ListTransactions(userID int64, txnType string, cursorID int64, limit int) ([]service.AccountTransactionItem, error) {
	ret := _m.Called(userID, txnType, cursorID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListTransactions")
	}

	var r0 []service.AccountTransactionItem
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string, int64, int) ([]service.AccountTransactionItem, error)); ok {
		return rf(userID, txnType, cursorID, limit)
	}
	if rf, ok := ret.Get(0).(func(int64, string, int64, int) []service.AccountTransactionItem); ok {
		r0 = rf(userID, txnType, cursorID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.AccountTransactionItem)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string, int64, int) error); ok {
		r1 = rf(userID, txnType, cursorID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Recharge provides a mock function with given fields: userID, amount, currency
func (_m *MockAccountService) Recharge(userID int64, amount float64, currency string) (*service.RechargeResult, error) {
	ret := _m.Called(userID, amount, currency)

	if len(ret) == 0 {
		panic("no return value specified for Recharge")
	}

	var r0 *service.RechargeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, float64, string) (*service.RechargeResult, error)); ok {
		return rf(userID, amount, currency)
	}
	if rf, ok := ret.Get(0).(func(int64, float64, string) *service.RechargeResult); ok {
		r0 = rf(userID, amount, currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.RechargeResult)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, float64, string) error); ok {
		r1 = rf(userID, amount, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
