// Code generated by mockery. DO NOT EDIT.

package mock

import (
	event "github.com/nusiss-capstone-project/campaign-center-api/server/event"
	mock "github.com/stretchr/testify/mock"
)

// MockCampaignRewardNotifier is an autogenerated mock type for the CampaignRewardNotifier type
type MockCampaignRewardNotifier struct {
	mock.Mock
}

// NotifyTopUpReward provides a mock function with given fields: _a0
func (_m *MockCampaignRewardNotifier) NotifyTopUpReward(_a0 event.TopUpRewardEvent) {
	_m.Called(_a0)
}

// NewMockCampaignRewardNotifier creates a new instance of MockCampaignRewardNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignRewardNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignRewardNotifier {
	mock := &MockCampaignRewardNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
