// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	mysql "github.com/nusiss-capstone-project/campaign-center-api/server/repository/mysql"
	model "github.com/nusiss-capstone-project/campaign-center-api/server/repository/mysql/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCampaignRepository is an autogenerated mock type for the CampaignRepository type
type MockCampaignRepository struct {
	mock.Mock
}

// Count provides a mock function with given fields: q
func (_m *MockCampaignRepository) Count(q mysql.CampaignQuery) (int64, error) {
	ret := _m.Called(q)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(mysql.CampaignQuery) (int64, error)); ok {
		return rf(q)
	}
	if rf, ok := ret.Get(0).(func(mysql.CampaignQuery) int64); ok {
		r0 = rf(q)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(mysql.CampaignQuery) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, c
func (_m *MockCampaignRepository) Create(ctx context.Context, c *model.Campaign) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Campaign) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: q, offset, limit
func (_m *MockCampaignRepository) Find(q mysql.CampaignQuery, offset int, limit int) ([]model.Campaign, error) {
	ret := _m.Called(q, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(mysql.CampaignQuery, int, int) ([]model.Campaign, error)); ok {
		return rf(q, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(mysql.CampaignQuery, int, int) []model.Campaign); ok {
		r0 = rf(q, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(mysql.CampaignQuery, int, int) error); ok {
		r1 = rf(q, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockCampaignRepository) GetByID(id int64) (*model.Campaign, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*model.Campaign, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.Campaign); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIDContext provides a mock function with given fields: ctx, id
func (_m *MockCampaignRepository) GetByIDContext(ctx context.Context, id int64) (*model.Campaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDContext")
	}

	var r0 *model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Campaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Campaign); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, c
func (_m *MockCampaignRepository) Update(ctx context.Context, c *model.Campaign) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Campaign) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, operator
func (_m *MockCampaignRepository) UpdateStatus(ctx context.Context, id int64, status int16, operator string) (*model.Campaign, error) {
	ret := _m.Called(ctx, id, status, operator)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *model.Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int16, string) (*model.Campaign, error)); ok {
		return rf(ctx, id, status, operator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int16, string) *model.Campaign); ok {
		r0 = rf(ctx, id, status, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int16, string) error); ok {
		r1 = rf(ctx, id, status, operator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCampaignRepository creates a new instance of MockCampaignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCampaignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCampaignRepository {
	mock := &MockCampaignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
