// Code generated by mockery. DO NOT EDIT.

package mock

import (
	context "context"

	model "github.com/nusiss-capstone-project/campaign-center-api/server/repository/mysql/model"
	mock "github.com/stretchr/testify/mock"
)

// MockParticipantRepository is an autogenerated mock type for the ParticipantRepository type
type MockParticipantRepository struct {
	mock.Mock
}

// GetByCampaignAndUser provides a mock function with given fields: campaignID, userID
func (_m *MockParticipantRepository) GetByCampaignAndUser(campaignID int64, userID int64) (*model.CampaignParticipant, error) {
	ret := _m.Called(campaignID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCampaignAndUser")
	}

	var r0 *model.CampaignParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64) (*model.CampaignParticipant, error)); ok {
		return rf(campaignID, userID)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) *model.CampaignParticipant); ok {
		r0 = rf(campaignID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CampaignParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(campaignID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Join provides a mock function with given fields: ctx, campaignID, userID
func (_m *MockParticipantRepository) Join(ctx context.Context, campaignID int64, userID int64) (*model.CampaignParticipant, error) {
	ret := _m.Called(ctx, campaignID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Join")
	}

	var r0 *model.CampaignParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*model.CampaignParticipant, error)); ok {
		return rf(ctx, campaignID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *model.CampaignParticipant); ok {
		r0 = rf(ctx, campaignID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CampaignParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, campaignID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByCampaignID provides a mock function with given fields: campaignID
func (_m *MockParticipantRepository) ListByCampaignID(campaignID int64) ([]model.CampaignParticipant, error) {
	ret := _m.Called(campaignID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCampaignID")
	}

	var r0 []model.CampaignParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]model.CampaignParticipant, error)); ok {
		return rf(campaignID)
	}
	if rf, ok := ret.Get(0).(func(int64) []model.CampaignParticipant); ok {
		r0 = rf(campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CampaignParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListJoinedCampaignIDs provides a mock function with given fields: userID, campaignIDs
func (_m *MockParticipantRepository) ListJoinedCampaignIDs(userID int64, campaignIDs []int64) (map[int64]struct{}, error) {
	ret := _m.Called(userID, campaignIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListJoinedCampaignIDs")
	}

	var r0 map[int64]struct{}
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, []int64) (map[int64]struct{}, error)); ok {
		return rf(userID, campaignIDs)
	}
	if rf, ok := ret.Get(0).(func(int64, []int64) map[int64]struct{}); ok {
		r0 = rf(userID, campaignIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]struct{})
		}
	}

	if rf, ok := ret.Get(1).(func(int64, []int64) error); ok {
		r1 = rf(userID, campaignIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockParticipantRepository creates a new instance of MockParticipantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantRepository {
	mock := &MockParticipantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
