// Code generated by mockery. DO NOT EDIT.

package mock

import (
	mysql "github.com/nusiss-capstone-project/campaign-center-api/server/repository/mysql"
	model "github.com/nusiss-capstone-project/campaign-center-api/server/repository/mysql/model"
	mock "github.com/stretchr/testify/mock"
)

// MockParticipantRepository is an autogenerated mock type for the ParticipantRepository type
type MockParticipantRepository struct {
	mock.Mock
}

// ListByCampaign provides a mock function with given fields: filter
func (_m *MockParticipantRepository) ListByCampaign(filter mysql.ParticipationListFilter) ([]model.CampaignParticipant, int64, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for ListByCampaign")
	}

	var r0 []model.CampaignParticipant
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(mysql.ParticipationListFilter) ([]model.CampaignParticipant, int64, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(mysql.ParticipationListFilter) []model.CampaignParticipant); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CampaignParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(mysql.ParticipationListFilter) int64); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(mysql.ParticipationListFilter) error); ok {
		r2 = rf(filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockParticipantRepository creates a new instance of MockParticipantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantRepository {
	mock := &MockParticipantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
