// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/user.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	CampaignCenterService_SayHello_FullMethodName = "/userpb.CampaignCenterService/SayHello"
)

type CampaignCenterServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type campaignCenterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignCenterServiceClient(cc grpc.ClientConnInterface) CampaignCenterServiceClient {
	return &campaignCenterServiceClient{cc}
}

func (c *campaignCenterServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, CampaignCenterService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type CampaignCenterServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedCampaignCenterServiceServer()
}

type UnimplementedCampaignCenterServiceServer struct{}

func (UnimplementedCampaignCenterServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedCampaignCenterServiceServer) mustEmbedUnimplementedCampaignCenterServiceServer() {
}
func (UnimplementedCampaignCenterServiceServer) testEmbeddedByValue() {}

type UnsafeCampaignCenterServiceServer interface {
	mustEmbedUnimplementedCampaignCenterServiceServer()
}

func RegisterCampaignCenterServiceServer(s grpc.ServiceRegistrar, srv CampaignCenterServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CampaignCenterService_ServiceDesc, srv)
}

func _CampaignCenterService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignCenterServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignCenterService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignCenterServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var CampaignCenterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userpb.CampaignCenterService",
	HandlerType: (*CampaignCenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{{
		MethodName: "SayHello",
		Handler:    _CampaignCenterService_SayHello_Handler,
	}},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user.proto",
}
