// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/campaign.proto

package campaignpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CampaignCenterService_SayHello_FullMethodName = "/campaignpb.CampaignCenterService/SayHello"
)

// CampaignCenterServiceClient is the client API for CampaignCenterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignCenterServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type campaignCenterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignCenterServiceClient(cc grpc.ClientConnInterface) CampaignCenterServiceClient {
	return &campaignCenterServiceClient{cc}
}

func (c *campaignCenterServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, CampaignCenterService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignCenterServiceServer is the server API for CampaignCenterService service.
// All implementations must embed UnimplementedCampaignCenterServiceServer
// for forward compatibility.
type CampaignCenterServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedCampaignCenterServiceServer()
}

// UnimplementedCampaignCenterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCampaignCenterServiceServer struct{}

func (UnimplementedCampaignCenterServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedCampaignCenterServiceServer) mustEmbedUnimplementedCampaignCenterServiceServer() {}
func (UnimplementedCampaignCenterServiceServer) testEmbeddedByValue()                               {}

// UnsafeCampaignCenterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignCenterServiceServer will
// result in compilation errors.
type UnsafeCampaignCenterServiceServer interface {
	mustEmbedUnimplementedCampaignCenterServiceServer()
}

func RegisterCampaignCenterServiceServer(s grpc.ServiceRegistrar, srv CampaignCenterServiceServer) {
	// If the following call panics, it indicates UnimplementedCampaignCenterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CampaignCenterService_ServiceDesc, srv)
}

func _CampaignCenterService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignCenterServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignCenterService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignCenterServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CampaignCenterService_ServiceDesc is the grpc.ServiceDesc for CampaignCenterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CampaignCenterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "campaignpb.CampaignCenterService",
	HandlerType: (*CampaignCenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _CampaignCenterService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/campaign.proto",
}
