http:
  host: 0.0.0.0
  port: 8080
log:
  level: info
grpc:
  host: 0.0.0.0
  port: 5000
  connect_timeout: 5
  max_pool_size: 100
mysql:
  enabled: true
  host: 10.249.36.74
  port: "3306"
  userName: campaign_dev
  password: "YV8d3vz68wPw1eYF"
  dbName: campaign_center
redis:
  enabled: false
  host: 127.0.0.1
  port: "6379"
