// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/campaigns": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-campaign"
                ],
                "summary": "List campaigns (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 10)",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Campaign status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Campaign ID filter",
                        "name": "campaignId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "items": {
                                                    "type": "array",
                                                    "items": {
                                                        "$ref": "#/definitions/data.CampaignListVO"
                                                    }
                                                },
                                                "total": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-campaign"
                ],
                "summary": "Create campaign (admin)",
                "parameters": [
                    {
                        "description": "Campaign name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.CreateCampaignReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "campaignId": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/campaigns/{campaignId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-campaign"
                ],
                "summary": "Get campaign detail (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.CampaignVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/campaigns/{campaignId}/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-campaign"
                ],
                "summary": "Publish campaign (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Operator",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.PublishOperatorReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.CampaignVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/campaigns/{campaignId}/users": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-participant"
                ],
                "summary": "List campaign participants (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.AdminParticipantListData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "campaign not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/campaigns/{campaignId}/users/{userId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-participant"
                ],
                "summary": "Get campaign participant detail (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.AdminParticipantVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/campaigns/{campaignId}/versions": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-campaign"
                ],
                "summary": "Create campaign version (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success; returns existing draft version when latest is still draft",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "properties": {
                                                "campaignId": {
                                                    "type": "integer"
                                                },
                                                "version": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/campaigns/{campaignId}/versions/{version}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-campaign"
                ],
                "summary": "Edit campaign draft version (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Draft content; read-only fields are ignored",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.CampaignVO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated campaign draft",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.CampaignVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "409": {
                        "description": "not editable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/images/upload": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-images"
                ],
                "summary": "Upload image (admin)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file (jpg/png/webp/gif, max 5MB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.ImageUploadData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "oss not configured",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/landing-pages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "List landing pages (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Default language filter e.g. en",
                        "name": "defaultLang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.LandingPageListData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "Create landing page (admin)",
                "parameters": [
                    {
                        "description": "Landing page content",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.LandingPageBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.LandingPageCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/landing-pages/{landingPageId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "Get landing page (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Landing page ID",
                        "name": "landingPageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Requested language (falls back to default)",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.LandingPageDetailVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "Update landing page (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Landing page ID",
                        "name": "landingPageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Landing page content",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.LandingPageBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.LandingPageUpdateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "409": {
                        "description": "not draft",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/landing-pages/{landingPageId}/detail/{lang}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "Get landing page detail by locale (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Landing page ID",
                        "name": "landingPageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Locale tag, e.g. ja, zh-CN",
                        "name": "lang",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.LandingPageDetailVO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid path",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/landing-pages/{landingPageId}/publish": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "Publish landing page (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Landing page ID",
                        "name": "landingPageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Operator",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.PublishOperatorReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.LandingPagePublishResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/landing-pages/{landingPageId}/translations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "List translated locales for a landing page (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Landing page ID",
                        "name": "landingPageId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.LandingPageTranslatedLangsData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid path",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "landing page not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/landing-pages/{landingPageId}/translations/generate": {
            "post": {
                "description": "Returns LLM-translated title/description/terms/steps/faq. Does not persist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "Generate landing page translation preview (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Landing page ID",
                        "name": "landingPageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Source/target languages and optional source copy",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.GenerateLandingTranslationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.GenerateLandingTranslationData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "validation or empty source",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "landing page not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "OpenAI not configured or database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/admin/landing-pages/{landingPageId}/translations/{lang}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-landing-page"
                ],
                "summary": "Upsert landing page translation (admin)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Landing page ID",
                        "name": "landingPageId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "BCP-47 or short language tag, e.g. ja, zh-CN",
                        "name": "lang",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Translated fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/data.PutLandingTranslationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.PutLandingTranslationData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "landing page not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "example: {\\\"message\\\":\\\"pong\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/web/campaigns": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-campaign"
                ],
                "summary": "List available campaigns (user)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Preferred language for landing-page title; default en",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.WebCampaignListData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/web/campaigns/{campaignId}/join": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-campaign"
                ],
                "summary": "Join campaign (user)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.WebJoinCampaignData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "campaign not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        },
        "/web/campaigns/{campaignId}/landing-page": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-campaign"
                ],
                "summary": "Get campaign landing page (user)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Preferred language; default en",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/data.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/data.WebCampaignLandingPageData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "campaign not found",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    },
                    "503": {
                        "description": "database unavailable",
                        "schema": {
                            "$ref": "#/definitions/data.StandardResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "data.AdminParticipantCampaignVO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "project_id": {
                    "type": "integer"
                },
                "task_group_id": {
                    "type": "integer"
                }
            }
        },
        "data.AdminParticipantListData": {
            "type": "object",
            "properties": {
                "campaign": {
                    "$ref": "#/definitions/data.AdminParticipantCampaignVO"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.AdminParticipantVO"
                    }
                }
            }
        },
        "data.AdminParticipantVO": {
            "type": "object",
            "properties": {
                "joined_at": {
                    "type": "integer"
                },
                "risk_level": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "data.BudgetVO": {
            "type": "object",
            "properties": {
                "projectId": {
                    "type": "integer"
                },
                "projectName": {
                    "type": "string"
                }
            }
        },
        "data.CampaignListVO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "integer"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "data.CampaignRewardRuleVO": {
            "type": "object",
            "properties": {
                "campaignId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "taskGroupId": {
                    "type": "integer"
                },
                "taskGroupReward": {
                    "type": "integer"
                },
                "taskRewardItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.TaskRewardItemVO"
                    }
                }
            }
        },
        "data.CampaignVO": {
            "type": "object",
            "properties": {
                "budgets": {
                    "$ref": "#/definitions/data.BudgetVO"
                },
                "campaignEndTime": {
                    "type": "integer"
                },
                "campaignStartTime": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "landingPageId": {
                    "type": "integer"
                },
                "market": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registrationEndTime": {
                    "type": "integer"
                },
                "registrationStartTime": {
                    "type": "integer"
                },
                "rewardRules": {
                    "$ref": "#/definitions/data.CampaignRewardRuleVO"
                },
                "status": {
                    "type": "integer"
                },
                "targetUserGroups": {
                    "$ref": "#/definitions/data.TargetUserGroupVO"
                },
                "timeZone": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "integer"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "data.CreateCampaignReq": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "data.GenerateLandingTranslationData": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "faq": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "lang": {
                    "type": "string",
                    "example": "ja"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "terms": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "data.GenerateLandingTranslationReq": {
            "type": "object",
            "required": [
                "sourceLang",
                "targetLang"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "faq": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "sourceLang": {
                    "type": "string",
                    "example": "en"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "targetLang": {
                    "type": "string",
                    "example": "ja"
                },
                "terms": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "data.ImageUploadData": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "data.LandingPageBody": {
            "type": "object",
            "required": [
                "bannerImageUrl",
                "defaultLang",
                "description",
                "terms",
                "title"
            ],
            "properties": {
                "bannerImageUrl": {
                    "type": "string"
                },
                "defaultLang": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "faq": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "terms": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "data.LandingPageCreateResp": {
            "type": "object",
            "properties": {
                "bannerImageUrl": {
                    "type": "string"
                },
                "defaultLang": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "faq": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "landingPageId": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "terms": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "data.LandingPageDetailVO": {
            "type": "object",
            "properties": {
                "bannerImageUrl": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "defaultLang": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "faq": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "lang": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "terms": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "data.LandingPageListData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageListItemVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "data.LandingPageListItemVO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "defaultLang": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "data.LandingPagePublishResp": {
            "type": "object",
            "properties": {
                "landingPageId": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "data.LandingPageRepeatableItemVO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "data.LandingPageTranslatedLangsData": {
            "type": "object",
            "properties": {
                "langs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "data.LandingPageUpdateResp": {
            "type": "object",
            "properties": {
                "bannerImageUrl": {
                    "type": "string"
                },
                "defaultLang": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "faq": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "landingPageId": {
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "terms": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "data.PublishOperatorReq": {
            "type": "object",
            "required": [
                "operator"
            ],
            "properties": {
                "operator": {
                    "type": "string"
                }
            }
        },
        "data.PutLandingTranslationData": {
            "type": "object",
            "properties": {
                "landingPageId": {
                    "type": "integer"
                },
                "lang": {
                    "type": "string"
                }
            }
        },
        "data.PutLandingTranslationReq": {
            "type": "object",
            "required": [
                "description",
                "terms",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "faq": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "operator": {
                    "type": "string",
                    "example": "admin"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "terms": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "data.StandardResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {},
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "data.TargetUserGroupVO": {
            "type": "object",
            "properties": {
                "groupName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "data.TaskRewardItemVO": {
            "type": "object",
            "properties": {
                "rewardTemplateId": {
                    "type": "integer"
                },
                "rewardTemplateName": {
                    "type": "string"
                },
                "taskId": {
                    "type": "integer"
                },
                "taskName": {
                    "type": "string"
                }
            }
        },
        "data.WebCampaignLandingPageData": {
            "type": "object",
            "properties": {
                "campaignId": {
                    "type": "integer",
                    "example": 1001
                },
                "joined": {
                    "type": "boolean",
                    "example": false
                },
                "joinedAt": {
                    "type": "integer",
                    "example": 1717200000
                },
                "landingPage": {
                    "$ref": "#/definitions/data.WebLandingPageContent"
                },
                "market": {
                    "type": "string",
                    "example": "SG"
                },
                "name": {
                    "type": "string",
                    "example": "Summer Deposit Bonus"
                },
                "timeZone": {
                    "type": "string",
                    "example": "Asia/Singapore"
                },
                "userId": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "data.WebCampaignListData": {
            "type": "object",
            "properties": {
                "ongoing": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.WebCampaignListItem"
                    }
                },
                "upcoming": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.WebCampaignListItem"
                    }
                }
            }
        },
        "data.WebCampaignListItem": {
            "type": "object",
            "properties": {
                "campaignEndTime": {
                    "type": "integer",
                    "example": 1722470400
                },
                "campaignStartTime": {
                    "type": "integer",
                    "example": 1717200000
                },
                "id": {
                    "type": "integer",
                    "example": 1001
                },
                "joined": {
                    "type": "boolean",
                    "example": false
                },
                "landingPageId": {
                    "type": "integer",
                    "example": 2001
                },
                "market": {
                    "type": "string",
                    "example": "SG"
                },
                "status": {
                    "type": "integer",
                    "example": 2
                },
                "title": {
                    "type": "string",
                    "example": "Deposit and get a bonus"
                }
            }
        },
        "data.WebJoinCampaignData": {
            "type": "object",
            "properties": {
                "campaignId": {
                    "type": "integer",
                    "example": 1001
                },
                "joined": {
                    "type": "boolean",
                    "example": true
                },
                "joinedAt": {
                    "type": "integer",
                    "example": 1717200000
                },
                "message": {
                    "type": "string",
                    "example": "joined"
                },
                "userId": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "data.WebLandingPageContent": {
            "type": "object",
            "properties": {
                "bannerImageUrl": {
                    "type": "string",
                    "example": "https://cdn.example.com/banner.png"
                },
                "description": {
                    "type": "string",
                    "example": "Join the campaign and complete the deposit task."
                },
                "faq": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "lang": {
                    "type": "string",
                    "example": "en"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/data.LandingPageRepeatableItemVO"
                    }
                },
                "terms": {
                    "type": "string",
                    "example": "One reward per user."
                },
                "title": {
                    "type": "string",
                    "example": "Deposit and get a bonus"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/campaign-center-api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Campaign Center API",
	Description:      "HTTP API for campaign center (admin campaign/landing-page + user campaign mocks). Operates under `/campaign-center-api/v1`;",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
