// Code generated by mockery. DO NOT EDIT.

package mock

import (
	mysql "github.com/lianjin/campaign-center-api/server/repository/mysql"
	model "github.com/lianjin/campaign-center-api/server/repository/mysql/model"
	mock "github.com/stretchr/testify/mock"
)

// MockLandingPageRepository is an autogenerated mock type for the LandingPageRepository type
type MockLandingPageRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: p
func (_m *MockLandingPageRepository) Create(p *model.CampaignLandingPage) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.CampaignLandingPage) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *MockLandingPageRepository) GetByID(id int64) (*model.CampaignLandingPage, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.CampaignLandingPage
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*model.CampaignLandingPage, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *model.CampaignLandingPage); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CampaignLandingPage)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: f
func (_m *MockLandingPageRepository) List(f mysql.LandingPageListFilter) ([]model.CampaignLandingPage, int64, error) {
	ret := _m.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.CampaignLandingPage
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(mysql.LandingPageListFilter) ([]model.CampaignLandingPage, int64, error)); ok {
		return rf(f)
	}
	if rf, ok := ret.Get(0).(func(mysql.LandingPageListFilter) []model.CampaignLandingPage); ok {
		r0 = rf(f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CampaignLandingPage)
		}
	}

	if rf, ok := ret.Get(1).(func(mysql.LandingPageListFilter) int64); ok {
		r1 = rf(f)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(mysql.LandingPageListFilter) error); ok {
		r2 = rf(f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Publish provides a mock function with given fields: id, operator
func (_m *MockLandingPageRepository) Publish(id int64, operator string) (*model.CampaignLandingPage, error) {
	ret := _m.Called(id, operator)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *model.CampaignLandingPage
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (*model.CampaignLandingPage, error)); ok {
		return rf(id, operator)
	}
	if rf, ok := ret.Get(0).(func(int64, string) *model.CampaignLandingPage); ok {
		r0 = rf(id, operator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CampaignLandingPage)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(id, operator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: p
func (_m *MockLandingPageRepository) Update(p *model.CampaignLandingPage) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.CampaignLandingPage) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockLandingPageRepository creates a new instance of MockLandingPageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLandingPageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLandingPageRepository {
	mock := &MockLandingPageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
