// Code generated by mockery. DO NOT EDIT.

package mock

import (
	model "github.com/lianjin/campaign-center-api/server/repository/mysql/model"
	mock "github.com/stretchr/testify/mock"
)

// MockParticipantRepository is an autogenerated mock type for the ParticipantRepository type
type MockParticipantRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: p
func (_m *MockParticipantRepository) Create(p *model.CampaignParticipant) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.CampaignParticipant) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByCampaignAndUser provides a mock function with given fields: campaignID, userID
func (_m *MockParticipantRepository) GetByCampaignAndUser(campaignID int64, userID int64) (*model.CampaignParticipant, error) {
	ret := _m.Called(campaignID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCampaignAndUser")
	}

	var r0 *model.CampaignParticipant
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64) (*model.CampaignParticipant, error)); ok {
		return rf(campaignID, userID)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) *model.CampaignParticipant); ok {
		r0 = rf(campaignID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CampaignParticipant)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(campaignID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: p
func (_m *MockParticipantRepository) Save(p *model.CampaignParticipant) error {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.CampaignParticipant) error); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockParticipantRepository creates a new instance of MockParticipantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantRepository {
	mock := &MockParticipantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
