// Code generated by mockery. DO NOT EDIT.

package mock

import (
	model "github.com/lianjin/campaign-center-api/server/repository/mysql/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRewardTransactionRepository is an autogenerated mock type for the RewardTransactionRepository type
type MockRewardTransactionRepository struct {
	mock.Mock
}

// CommitGrantWithParticipant provides a mock function with given fields: participant, reward
func (_m *MockRewardTransactionRepository) CommitGrantWithParticipant(participant *model.CampaignParticipant, reward *model.RewardTransaction) error {
	ret := _m.Called(participant, reward)

	if len(ret) == 0 {
		panic("no return value specified for CommitGrantWithParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.CampaignParticipant, *model.RewardTransaction) error); ok {
		r0 = rf(participant, reward)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: t
func (_m *MockRewardTransactionRepository) Create(t *model.RewardTransaction) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.RewardTransaction) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRewardTransactionRepository creates a new instance of MockRewardTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRewardTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRewardTransactionRepository {
	mock := &MockRewardTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
