name: Deploy to Railway
on:
  push:
    branches: [main, develop] # 分支关联环境

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/develop'
        working-directory: server
        run: railway up --detach -e dev
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_DEV }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        working-directory: server
        run: railway up --detach -e production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}